export const products = [
 {id:'pulse-headphones',name:'Pulse Wireless',category:'Audio',price:68500,old_price:80000,tag:'Bestseller',description:'Find your focus. Over-ear wireless headphones with soft cushions, active noise cancellation, and up to 40 hours of listening.',specs:['40-hour battery','Active noise cancellation','USB-C charging'],image:'/products/headphones.jpg',stock:24},
 {id:'air-earbuds',name:'Air Buds Pro',category:'Audio',price:42500,old_price:0,tag:'New arrival',description:'Big sound, small footprint. Lightweight wireless earbuds made for your commute, calls, and everything in between.',specs:['24 hours with case','Touch controls','Splash resistant'],image:'/products/earbuds.jpg',stock:35},
 {id:'key-keyboard',name:'Key Mechanical',category:'Workspace',price:55000,old_price:65000,tag:'',description:'Make every keystroke count. A compact mechanical keyboard with a satisfying feel and a clean desktop footprint.',specs:['Compact layout','Tactile switches','Wired USB-C'],image:'/products/keyboard.jpg',stock:18},
 {id:'roam-speaker',name:'Roam Speaker',category:'Audio',price:38000,old_price:0,tag:'',description:'Your soundtrack, wherever you go. A compact Bluetooth speaker with rich sound and a rugged, travel-ready design.',specs:['12-hour battery','Bluetooth 5.3','Portable design'],image:'/products/speaker.jpg',stock:20},
 {id:'link-hub',name:'Link USB-C Hub',category:'Accessories',price:28500,old_price:0,tag:'',description:'One connection. More possibilities. Expand your laptop with the ports you need for a productive day.',specs:['6-in-1 connectivity','HDMI output','USB-C power delivery'],image:'/products/hub.jpg',stock:40},
 {id:'glide-mouse',name:'Glide Wireless',category:'Workspace',price:24000,old_price:30000,tag:'Everyday essential',description:'A smoother way to work. A comfortable wireless mouse with precise tracking and quiet clicks.',specs:['Quiet clicks','Adjustable sensitivity','Wireless connection'],image:'/products/mouse.jpg',stock:30},
{"id": "orbit-watch", "name": "Orbit Smartwatch", "category": "Wearables", "price": 48500, "old_price": 0, "tag": "New arrival", "description": "A little more movement, a little more connection. A lightweight everyday smartwatch for activity tracking and notifications.", "specs": ["Activity tracking", "Phone notifications", "Adjustable silicone strap"], "image": "/products/orbit-watch.svg", "stock": 18},
{"id": "charge-powerbank", "name": "Charge Power Bank", "category": "Accessories", "price": 32000, "old_price": 0, "tag": "New arrival", "description": "Keep your essentials powered while you are out. A compact portable battery for commutes and busy days.", "specs": ["10,000 mAh capacity", "USB-C charging", "Battery level display"], "image": "/products/charge-powerbank.svg", "stock": 30},
{"id": "arc-controller", "name": "Arc Gamepad", "category": "Gaming", "price": 39500, "old_price": 0, "tag": "New arrival", "description": "Settle into your next session with a comfortable controller built for responsive everyday play.", "specs": ["Wireless connectivity", "Dual analogue sticks", "USB-C charging"], "image": "/products/arc-controller.svg", "stock": 16},
{"id": "focus-webcam", "name": "Focus Webcam", "category": "Workspace", "price": 36500, "old_price": 0, "tag": "New arrival", "description": "Show up clearly for meetings, lessons, and catch-ups with a compact webcam that sits neatly above your screen.", "specs": ["1080p video", "Built-in microphone", "Adjustable monitor clip"], "image": "/products/focus-webcam.svg", "stock": 20},
{"id": "lift-laptop-stand", "name": "Lift Laptop Stand", "category": "Workspace", "price": 22500, "old_price": 0, "tag": "New arrival", "description": "Give your screen a comfortable lift and your desk a little breathing room with a foldable laptop stand.", "specs": ["Adjustable angle", "Foldable aluminium frame", "Non-slip contact pads"], "image": "/products/lift-laptop-stand.svg", "stock": 28},
{"id": "spark-wall-charger", "name": "Spark USB-C Charger", "category": "Accessories", "price": 19500, "old_price": 0, "tag": "New arrival", "description": "A compact charging companion for your desk or travel bag, with a convenient USB-C connection.", "specs": ["30W USB-C output", "Compact design", "UK-style three-pin plug"], "image": "/products/spark-wall-charger.svg", "stock": 40},
{"id": "vault-portable-ssd", "name": "Vault Portable SSD", "category": "Accessories", "price": 89000, "old_price": 0, "tag": "New arrival", "description": "Keep projects, photos, and everyday files close with a pocket-sized portable drive.", "specs": ["512 GB storage", "USB-C connection", "Compact metal enclosure"], "image": "/products/vault-portable-ssd.svg", "stock": 14},
{"id": "beam-desk-light", "name": "Beam Desk Light", "category": "Workspace", "price": 27500, "old_price": 0, "tag": "New arrival", "description": "Set the mood for focused work or a quiet evening with a slim, adjustable desk light.", "specs": ["Three light modes", "Adjustable arm", "USB powered"], "image": "/products/beam-desk-light.svg", "stock": 22}
];
export type Product = typeof products[number];
export const money=(v:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(v);
