export const products = [
 {id:'pulse-headphones',name:'Pulse Wireless',category:'Audio',price:68500,old_price:80000,tag:'Bestseller',description:'Find your focus. Over-ear wireless headphones with soft cushions, active noise cancellation, and up to 40 hours of listening.',specs:['40-hour battery','Active noise cancellation','USB-C charging'],image:'/products/headphones.jpg',stock:24},
 {id:'air-earbuds',name:'Air Buds Pro',category:'Audio',price:42500,old_price:0,tag:'New arrival',description:'Big sound, small footprint. Lightweight wireless earbuds made for your commute, calls, and everything in between.',specs:['24 hours with case','Touch controls','Splash resistant'],image:'/products/earbuds.jpg',stock:35},
 {id:'key-keyboard',name:'Key Mechanical',category:'Workspace',price:55000,old_price:65000,tag:'',description:'Make every keystroke count. A compact mechanical keyboard with a satisfying feel and a clean desktop footprint.',specs:['Compact layout','Tactile switches','Wired USB-C'],image:'/products/keyboard.jpg',stock:18},
 {id:'roam-speaker',name:'Roam Speaker',category:'Audio',price:38000,old_price:0,tag:'',description:'Your soundtrack, wherever you go. A compact Bluetooth speaker with rich sound and a rugged, travel-ready design.',specs:['12-hour battery','Bluetooth 5.3','Portable design'],image:'/products/speaker.jpg',stock:20},
 {id:'link-hub',name:'Link USB-C Hub',category:'Accessories',price:28500,old_price:0,tag:'',description:'One connection. More possibilities. Expand your laptop with the ports you need for a productive day.',specs:['6-in-1 connectivity','HDMI output','USB-C power delivery'],image:'/products/hub.jpg',stock:40},
 {id:'glide-mouse',name:'Glide Wireless',category:'Workspace',price:24000,old_price:30000,tag:'Everyday essential',description:'A smoother way to work. A comfortable wireless mouse with precise tracking and quiet clicks.',specs:['Quiet clicks','Adjustable sensitivity','Wireless connection'],image:'/products/mouse.jpg',stock:30}
];
export type Product = typeof products[number];
export const money=(v:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(v);
